### ISSUE TITLE
Add check to startgame to ensure array is passed in

### ISSUE THREAD

**Issue by bjbestdev** [nic-dgl213-f21/dgl213-module1-ItsJustJarvis#2]

**Comment by ItsJustJarvis** [comment]
I have added a check to ensure an array is passed in as opposed to a different value. I tried to determine whether this was the approach expected. Please inform me if I am missing something, so that I may learn for next time. Additionally I thought that start game could use some refactoring so I relocated some of the player initialization to its own function.
